name: 🐛 Bug Report
description: Report something that isn’t working as expected
title: "[BUG] <short summary>"
labels: ["bug"]
assignees: [],

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue in detail.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do we trigger the bug?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen instead?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: e.g. OS, browser, Node.js version, device
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this bug?
      options:
        - Blocker 🚨
        - High 🔴
        - Medium 🟠
        - Low 🟢
        - Deferred 💤
        - Trivial ⚪
    validations:
      required: true
