name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] <short summary>"
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Opportunity
      description: What are you trying to solve or improve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed idea or feature.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Related discussions, links, screenshots, etc.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Blocker 🚨
        - High 🔴
        - Medium 🟠
        - Low 🟢
        - Deferred 💤
        - Trivial ⚪
    validations:
      required: true
